apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  selector:
    app: productservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4000
      nodePort: 31111
